# Generated by Django 4.1.5 on 2023-04-22 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_user', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('nb_user', models.CharField(max_length=200, unique=True)),
                ('passwd_user', models.CharField(max_length=200)),
                ('nick_name', models.CharField(max_length=200)),
                ('photo_user', models.ImageField(null=True, upload_to='imagen')),
                ('date_joined_user', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
