# Generated by Django 4.1.5 on 2023-04-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_rename_nick_name_user_nick_name_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_user',
            new_name='email',
        ),
    ]
