# Generated by Django 4.1.5 on 2023-04-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_rename_email_user_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='email_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
