# Generated by Django 4.1.5 on 2023-05-06 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0006_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_user',
            field=models.ImageField(default='/imagen/profile.png', null=True, upload_to='imagen'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
