# Generated by Django 4.1.5 on 2023-05-30 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0009_alter_token_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_user',
            field=models.ImageField(default='/imagen/users/profile.png', null=True, upload_to='imagen/users'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.CharField(max_length=200, unique=True)),
                ('tittle_post', models.CharField(max_length=200)),
                ('runes1', models.CharField(max_length=200)),
                ('runes2', models.CharField(max_length=200)),
                ('runes3', models.CharField(max_length=200)),
                ('runes4', models.CharField(max_length=200)),
                ('runes5', models.CharField(max_length=200)),
                ('runes6', models.CharField(max_length=200)),
                ('keystone', models.CharField(max_length=200)),
                ('items1', models.CharField(max_length=200)),
                ('items2', models.CharField(max_length=200)),
                ('items3', models.CharField(max_length=200)),
                ('items4', models.CharField(max_length=200)),
                ('items5', models.CharField(max_length=200)),
                ('items6', models.CharField(max_length=200)),
                ('summoner_spells1', models.CharField(max_length=200)),
                ('summoner_spells2', models.CharField(max_length=200)),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
