# Generated by Django 4.1.5 on 2023-06-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_alter_post_user_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='runes1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='runes2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='runes3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='runes4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='runes5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='runes6',
        ),
    ]
